exec_once:
 files:
  /etc/apache2/sites-enabled/orocrm.conf:
    name: orocrm.conf
    path: /etc/apache2/sites-enabled/
    mode: "0644"
    owner: root
    group: root
    content: |
      <VirtualHost *:80>
        DocumentRoot /var/www/html/orocrm
        <Directory /var/www/html/orocrm>
          AllowOverride All
          Order Allow,Deny
          Allow from All
        </Directory>

        CustomLog /var/log/apache2/access.log combined
        ErrorLog /var/log/apache2/error.log
      </VirtualHost>
 execs:
  Run composer install:
   name: Run composer install
   command: |
     #!/usr/bin/env bash
     export COMPOSER_HOME=/usr/local/bin/.composer 
     /usr/local/bin/composer install --no-interaction
post_app_deploy:
 execs:
  Restart apache:
   name: Restart apache
   command: |
     #!/usr/bin/env bash
     chown -RL www-data:www-data /var/www/html/orocrm
     service apache2 restart
